"""Generate sample knowledge data for frontend preview without AI step."""
import json

sample = {
    "nodes": [
        {"id": "java-basics", "title": "Java 基础", "summary": "Java 语言的核心基础概念，包含面向对象、集合、异常处理等", "parentId": None, "tags": ["Java", "基础"], "importance": 5, "source": "面渣逆袭 Java 集合框架篇.pdf"},
        {"id": "java-collections", "title": "Java 集合框架", "summary": "包含 List、Set、Map 及其实现类的数据结构体系", "parentId": "java-basics", "tags": ["Java", "集合"], "importance": 5, "source": "面渣逆袭 Java 集合框架篇.pdf"},
        {"id": "arraylist", "title": "ArrayList", "summary": "基于动态数组实现的 List，查询快增删慢", "parentId": "java-collections", "tags": ["Java", "集合"], "importance": 5, "source": "面渣逆袭 Java 集合框架篇.pdf"},
        {"id": "linkedlist", "title": "LinkedList", "summary": "基于双向链表实现的 List，增删快查询慢", "parentId": "java-collections", "tags": ["Java", "集合"], "importance": 4, "source": "面渣逆袭 Java 集合框架篇.pdf"},
        {"id": "hashmap", "title": "HashMap", "summary": "基于哈希表实现的 Map，JDK8+引入红黑树优化", "parentId": "java-collections", "tags": ["Java", "集合"], "importance": 5, "source": "面渣逆袭 Java 集合框架篇.pdf"},
        {"id": "concurrenthashmap", "title": "ConcurrentHashMap", "summary": "线程安全的 HashMap，JDK8+使用CAS+synchronized", "parentId": "java-collections", "tags": ["Java", "集合", "并发"], "importance": 5, "source": "面渣逆袭 Java 集合框架篇.pdf"},
        {"id": "java-concurrency", "title": "Java 并发编程", "summary": "多线程编程核心知识，包含锁、线程池、JUC等", "parentId": None, "tags": ["Java", "并发"], "importance": 5, "source": "面渣逆袭Java并发编程.pdf"},
        {"id": "thread-pool", "title": "线程池", "summary": "ThreadPoolExecutor 核心参数与工作原理", "parentId": "java-concurrency", "tags": ["Java", "并发"], "importance": 5, "source": "面渣逆袭Java并发编程.pdf"},
        {"id": "aqs", "title": "AQS", "summary": "AbstractQueuedSynchronizer，JUC 同步器基础框架", "parentId": "java-concurrency", "tags": ["Java", "并发"], "importance": 5, "source": "面渣逆袭Java并发编程.pdf"},
        {"id": "synchronized", "title": "synchronized", "summary": "Java 内置锁，从偏向锁到重量级锁的升级过程", "parentId": "java-concurrency", "tags": ["Java", "并发"], "importance": 5, "source": "面渣逆袭Java并发编程.pdf"},
        {"id": "jvm", "title": "JVM", "summary": "Java 虚拟机核心知识：内存模型、GC、类加载", "parentId": None, "tags": ["Java", "JVM"], "importance": 5, "source": "面渣逆袭 JVM.pdf"},
        {"id": "jvm-memory", "title": "JVM 内存模型", "summary": "堆、栈、方法区、程序计数器等运行时数据区域", "parentId": "jvm", "tags": ["Java", "JVM", "内存"], "importance": 5, "source": "面渣逆袭 JVM.pdf"},
        {"id": "jvm-gc", "title": "GC 垃圾回收", "summary": "垃圾回收算法（标记清除、复制、标记整理）与收集器", "parentId": "jvm", "tags": ["Java", "JVM", "GC"], "importance": 5, "source": "面渣逆袭 JVM.pdf"},
        {"id": "jvm-classloader", "title": "类加载机制", "summary": "双亲委派模型、类加载过程（加载-链接-初始化）", "parentId": "jvm", "tags": ["Java", "JVM"], "importance": 4, "source": "面渣逆袭 JVM.pdf"},
        {"id": "mysql", "title": "MySQL", "summary": "关系型数据库核心知识：索引、事务、锁、优化", "parentId": None, "tags": ["数据库", "MySQL"], "importance": 5, "source": "面渣逆袭 MySQL.pdf"},
        {"id": "mysql-index", "title": "MySQL 索引", "summary": "B+树索引结构、聚簇索引与非聚簇索引的区别", "parentId": "mysql", "tags": ["数据库", "MySQL"], "importance": 5, "source": "面渣逆袭 MySQL.pdf"},
        {"id": "mysql-transaction", "title": "MySQL 事务", "summary": "ACID 特性、隔离级别、MVCC 多版本并发控制", "parentId": "mysql", "tags": ["数据库", "MySQL"], "importance": 5, "source": "面渣逆袭 MySQL.pdf"},
        {"id": "mysql-lock", "title": "MySQL 锁机制", "summary": "行锁、表锁、间隙锁、意向锁及死锁排查", "parentId": "mysql", "tags": ["数据库", "MySQL"], "importance": 4, "source": "面渣逆袭 MySQL.pdf"},
        {"id": "redis", "title": "Redis", "summary": "高性能缓存数据库：数据结构、持久化、集群方案", "parentId": None, "tags": ["数据库", "Redis", "缓存"], "importance": 5, "source": "面渣逆袭 Redis 篇.pdf"},
        {"id": "redis-data-types", "title": "Redis 数据结构", "summary": "String、Hash、List、Set、ZSet 五种基础数据结构", "parentId": "redis", "tags": ["数据库", "Redis"], "importance": 5, "source": "面渣逆袭 Redis 篇.pdf"},
        {"id": "redis-cache-strategy", "title": "缓存策略", "summary": "缓存穿透、击穿、雪崩的解决方案", "parentId": "redis", "tags": ["数据库", "Redis", "缓存"], "importance": 5, "source": "面渣逆袭 Redis 篇.pdf"},
        {"id": "spring", "title": "Spring 框架", "summary": "Spring 核心：IoC、AOP、事务管理、Boot 自动配置", "parentId": None, "tags": ["Java", "Spring", "框架"], "importance": 5, "source": "面渣逆袭 Spring 篇.pdf"},
        {"id": "spring-ioc", "title": "Spring IoC", "summary": "控制反转与依赖注入，Bean 生命周期管理", "parentId": "spring", "tags": ["Java", "Spring"], "importance": 5, "source": "面渣逆袭 Spring 篇.pdf"},
        {"id": "spring-aop", "title": "Spring AOP", "summary": "面向切面编程：动态代理、切面、通知等核心概念", "parentId": "spring", "tags": ["Java", "Spring"], "importance": 4, "source": "面渣逆袭 Spring 篇.pdf"},
        {"id": "spring-boot", "title": "Spring Boot", "summary": "自动配置、起步依赖、内嵌服务器的快速开发框架", "parentId": "spring", "tags": ["Java", "Spring"], "importance": 5, "source": "面渣逆袭 Spring 篇.pdf"},
        {"id": "mybatis", "title": "MyBatis", "summary": "ORM 框架：映射配置、动态 SQL、缓存机制", "parentId": None, "tags": ["Java", "MyBatis", "ORM"], "importance": 4, "source": "面渣逆袭 MyBatis.pdf"},
        {"id": "network", "title": "计算机网络", "summary": "TCP/IP 协议栈、HTTP/HTTPS、DNS 等网络基础", "parentId": None, "tags": ["网络", "基础"], "importance": 5, "source": "面渣逆袭计算机网络.pdf"},
        {"id": "tcp", "title": "TCP 协议", "summary": "三次握手、四次挥手、拥塞控制、流量控制", "parentId": "network", "tags": ["网络", "TCP"], "importance": 5, "source": "面渣逆袭计算机网络.pdf"},
        {"id": "http", "title": "HTTP/HTTPS", "summary": "HTTP 各版本特性、HTTPS TLS 握手过程", "parentId": "network", "tags": ["网络", "HTTP"], "importance": 5, "source": "面渣逆袭计算机网络.pdf"},
        {"id": "os", "title": "操作系统", "summary": "进程线程、内存管理、文件系统、IO 模型", "parentId": None, "tags": ["操作系统", "基础"], "importance": 4, "source": "面渣逆袭操作系统.pdf"},
        {"id": "process-thread", "title": "进程与线程", "summary": "进程线程区别、上下文切换、进程间通信方式", "parentId": "os", "tags": ["操作系统", "并发"], "importance": 5, "source": "面渣逆袭操作系统.pdf"},
    ],
    "edges": [
        {"from": "java-collections", "to": "java-basics", "type": "contains", "description": "集合是 Java 基础的核心组成部分"},
        {"from": "arraylist", "to": "java-collections", "type": "contains", "description": "ArrayList 是 List 接口的主要实现"},
        {"from": "linkedlist", "to": "java-collections", "type": "contains", "description": "LinkedList 是 List 接口的链表实现"},
        {"from": "hashmap", "to": "java-collections", "type": "contains", "description": "HashMap 是最常用的 Map 实现"},
        {"from": "concurrenthashmap", "to": "hashmap", "type": "prerequisite", "description": "理解ConcurrentHashMap需先掌握HashMap"},
        {"from": "concurrenthashmap", "to": "java-concurrency", "type": "related", "description": "ConcurrentHashMap涉及并发编程核心思想"},
        {"from": "linkedlist", "to": "arraylist", "type": "compare", "description": "ArrayList查询快增删慢，LinkedList相反"},
        {"from": "thread-pool", "to": "java-concurrency", "type": "contains", "description": "线程池是并发编程的核心工具"},
        {"from": "aqs", "to": "java-concurrency", "type": "contains", "description": "AQS是JUC并发工具的基础框架"},
        {"from": "aqs", "to": "synchronized", "type": "compare", "description": "AQS是同步框架，synchronized是内置锁"},
        {"from": "synchronized", "to": "java-concurrency", "type": "contains", "description": "synchronized是Java并发的基础锁机制"},
        {"from": "jvm-memory", "to": "jvm", "type": "contains", "description": "内存模型是JVM核心组成部分"},
        {"from": "jvm-gc", "to": "jvm-memory", "type": "prerequisite", "description": "理解GC需要先了解JVM内存布局"},
        {"from": "jvm-classloader", "to": "jvm", "type": "contains", "description": "类加载机制是JVM的重要组成部分"},
        {"from": "mysql-index", "to": "mysql", "type": "contains", "description": "索引是MySQL查询优化的核心"},
        {"from": "mysql-transaction", "to": "mysql", "type": "contains", "description": "事务是保证数据一致性的核心机制"},
        {"from": "mysql-lock", "to": "mysql-transaction", "type": "prerequisite", "description": "锁机制是实现事务隔离的基础"},
        {"from": "redis-data-types", "to": "redis", "type": "contains", "description": "数据结构是Redis的基础"},
        {"from": "redis-cache-strategy", "to": "redis", "type": "contains", "description": "缓存策略是Redis面试高频考点"},
        {"from": "redis-cache-strategy", "to": "mysql", "type": "related", "description": "缓存与数据库一致性是常见面试题"},
        {"from": "spring-ioc", "to": "spring", "type": "contains", "description": "IoC是Spring框架的核心"},
        {"from": "spring-aop", "to": "spring", "type": "contains", "description": "AOP是Spring两大核心特性之一"},
        {"from": "spring-boot", "to": "spring", "type": "contains", "description": "Spring Boot简化了Spring应用的搭建"},
        {"from": "spring-ioc", "to": "java-basics", "type": "prerequisite", "description": "理解IoC需要Java反射和注解基础"},
        {"from": "tcp", "to": "network", "type": "contains", "description": "TCP是传输层核心协议"},
        {"from": "http", "to": "network", "type": "contains", "description": "HTTP是应用层核心协议"},
        {"from": "http", "to": "tcp", "type": "prerequisite", "description": "HTTP基于TCP协议"},
        {"from": "process-thread", "to": "os", "type": "contains", "description": "进程线程是操作系统的核心概念"},
        {"from": "process-thread", "to": "java-concurrency", "type": "prerequisite", "description": "理解Java并发需要操作系统进程线程基础"},
        {"from": "concurrenthashmap", "to": "synchronized", "type": "related", "description": "ConcurrentHashMap在JDK8+使用synchronized"},
        {"from": "jvm-gc", "to": "os", "type": "related", "description": "GC涉及内存管理，与OS内存管理相关"},
        {"from": "mybatis", "to": "spring", "type": "related", "description": "MyBatis常与Spring集成使用"},
    ],
}

with open("output/knowledge-data.json", "w", encoding="utf-8") as f:
    json.dump(sample, f, ensure_ascii=False, indent=2)

print(f"Sample data created: {len(sample['nodes'])} nodes, {len(sample['edges'])} edges")
